# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OnyxPoster' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnyxPoster
pod 'SVProgressHUD'
pod 'NVActivityIndicatorView'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'IQKeyboardManagerSwift'

pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'

end
