# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'OnyxStorer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnyxStorer
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SVProgressHUD'
pod 'NVActivityIndicatorView'
pod 'SwiftyJSON'
pod 'Alamofire'

end
